# 数据源
spring:
   datasource:
         url: jdbc:mysql://120.26.57.145:18306/zljc?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
         username: zljc
         password: zljc.daydayup.com.cn
